INSERT INTO mushroom (photoURL,
mushroom_name,
other_names,
edible,
consumable,
when_fruiting,
where_fruiting,
hat,
stem,
ring,
gills,
tubes,
pulp,
smell,
taste,
differentiation,
similar,
remarks,
food_value) VALUES
("chanterelle",
"chanterelle",
"chanterelle/pieprznik jadalny/kurka",
true,
"GREAT",
"summer-autumn",
"deciduous and coniferous forests, especially in mountains",
"3-10cm, yellow, at first convex, later concave, surface irregular, undulating, folded edge",
"massive, smooth, shape of an inverted cup",
"none",
"yellow, folded, twisted, bifurcated and running far away",
"none",
"yellowish, compact and fibrous",
"fruity",
"sweet to spicy",
"color from pale yellow to golden yellow, sometimes orange",
"false chanterelle",
"",
"edible, delicious, it can be prepared in many ways"),
("false-chanterelle",
"false-chanterelle",
"false chanterelle/lisówka pomarańczowa",
false,
"POISONOUS",
"autumn",
"deciduous and coniferous forests",
"2-7cm, at first inverted edge, later funnel-shaped, with folded or bent edges, orange-yellow",
"height 3–5 cm, thickness 3–10 mm, cylindrical at the bottom, widening up conically, color blackish at the base",
"none",
"thin, dense, bifurcating, tapering to the stem, sometimes folded",
"none",
"white or cream, juicy and soft",
"mild",
"bitter and sour",
"from yellow to orange-yellow and orange to red-orange",
"chanterelle",
"",
"inedible, when eaten in larger amounts, it can cause digestive disorders"),
("boletus",
"boletus",
"boletus/borowik",
true,
"GREAT",
"summer-autumn",
"deciduous and coniferous forests, in hilly and mountainous areas",
"5-25cm, brown, hemispherical, convex",
"5-20cm, massive, compact, cylindrical, bulky",
"none",
"none",
"whitish yellow, small round, spongy, thin and long",
"white, compact",
"typical mushroom",
"mild, mushroom",
"hat whitish, light and dark brown, brick red",
"bitter bolete",
"",
"delicious, you can eat it raw in a salad, bake, fry, marinate"),
("bitter-bolete",
"bitter-bolete",
"bitter bolete/goryczak żółciowy",
false,
"POISONOUS",
"summer-autumn",
"deciduous and coniferous forests, in hilly and mountainous areas",
"5-12cm, brown, hemispherical, convex",
"5-14cm, massive, bulky, covered with mesh",
"none",
"none",
"whitish pink, small round, spongy and long",
"white, soft",
"delicate",
"burning, bitter",
"hat light brown, yellowish",
"boletus",
"try to lick the bottom of the hat",
"poisonous"),
("leccinum-aurantiacum",
"leccinum-aurantiacum",
"leccinum aurantiacum/koźlarz czerwony",
true,
"GOOD",
"summer-autumn",
"deciduous forests, under aspens, willows",
"5-15cm, reddish, hemispherical, convex",
"6-20cm, cylindrical, covered with brown scales",
"none",
"none",
"gray, small, thin, long, soft",
"white, compact, soft",
"delicate, nice",
"mild",
"hat orange, redbrown, touched become bluish",
"other edible leccinum",
"",
"edible, good"),
("leccinum-carpini",
"leccinum-carpini",
"leccinum carpini/koźlarz grabowy",
true,
"GOOD",
"summer-beginning of autumn",
"deciduous forests, under hornbeams, birches, poplars and hazelnuts",
"3-12cm, brown-gray, fleshy, elastic, hemispherical, convex",
"8-14cm, cylindrical",
"none",
"none",
"whitish, small, round, spongy, long and narrow",
"white, soft in hat, fibrous in stem",
"slightly perceptible",
"mild",
"hat gray-brown, ashen, ocher, white",
"other edible leccinum",
"",
"good"),
("bay-bolete",
"bay-bolete",
"bay bolete/pogrzybek brunatny",
true,
"GOOD",
"summer-autumn",
"deciduous and coniferous forests, under oaks, chestnut and beech trees, in hilly and mountainous areas",
"4-15, brown, fleshy, compact, hemispherical, convex",
"4-12cm, thin and cylindrical or chubby and stocky, very hard",
"none",
"none",
"whitish, small",
"whitish, hard, compact",
"fruity",
"sweet",
"hat dark-brown to  darkening",
"bitter-bolete",
"",
"edible, tasty"),
("parasol-mushroom",
"parasol-mushroom",
"parasol mushroom/czubajka kania",
true,
"GREAT",
"summer-autumn",
"deciduous forests, sandy and gravel soil",
"10-30cm, spherical, convex, with scales",
"10-40cm, long, cylindrical, delicate",
"strong, membranous",
"whitish, dense and wide",
"none",
"white, in hat soft, in stem fibrous",
"nutty",
"nutty",
"hat grayish, light hazel, with dense scales",
"shaggy-parasol",
"",
"edible, hat after removal of scales, young can be eaten raw in salad, big hats can be grilled or fired"),
("shaggy-parasol",
"shaggy-parasol",
"shaggy-parasol/czubajka czerwieniejąca",
false,
"INEDIBLE",
"summer-autumn",
"meadows, forests, forests, gardens",
"8-20cm, brown, conical, flat",
"10-15cm, cylindrical, stocky, smooth, with a well-developed tuber",
"membranous and shifting",
"white, free, turning red when touched",
"none",
"white, in hat soft",
"strong, nice",
"mild",
"hat light to dark brown",
"parasol-mushroom",
"",
"inedible, can cause serious stomach problems"),
("toadstool",
"toadstool",
"toadstool/fly agaric/muchomor czerwony",
false,
"DEADLY_POISONOUS",
"summer-autumn",
"deciduous and coniferous forests",
"8-20cm, red, hemispherical, convex",
"10-25cm, cylindrical with a delicate scabbard",
"large, membranous",
"white, pale yellowish, dense",
"none",
"white",
"none",
"none",
"hat orange, red, gills sometimes yellow",
"imperial toadstool",
"",
"very poisonous, cause pain, vomiting, diarrhea, sweating, delirium, confusion, convulsions and finally a deep coma"),
("lactarius",
"lactarius",
"lactarius/saffron milk cap/red pine mushroom/mleczaj rydz",
true,
"GOOD",
"summer-beginning of autumn",
"coniferous forests, mountains",
"4-12cm, orange, convex, funnel-shaped",
"4-8cm, cylindrical, stocky, tapered at the base",
"none",
"orange, dense, thin and narrow",
"none",
"yellow, fragile, with carrot red milk",
"fruity",
"acidulous",
"hat yellowish to dark orange",
"other edible lactarius",
"",
"edible, excellent grilled, fried or in sauce"),
("changle",
"changle",
"changle/ramaria/gałęziak żółty",
true,
"AVERAGE",
"summer-autumn",
"deciduous and coniferous forests, in humid and shady places",
"none",
"5-15cm, coral-like",
"none",
"none",
"none",
"white, soft, brittle, watery",
"nice",
"bitterish",
"light yellow to sulfuric",
"",
"",
"edible, but only bases of young ones")








;