INSERT INTO mushroom (photoURL,
mushroom_name,
other_names,
edible,
consumable,
when_fruiting,
where_fruiting,
hat,
stem,
ring,
gills,
tubes,
pulp,
smell,
taste,
differentiation,
similar,
remarks,
food_value) VALUES
("chanterelle",
"chanterelle",
"pieprznik jadalny, kurka",
true,
"GREAT",
"summer-autumn",
"deciduous and coniferous forests, especially in mountains",
"3-10cm, yellow, at first convex, later concave, surface irregular, undulating, folded edge",
"massive, smooth, shape of an inverted cup",
"none",
"yellow, folded, twisted, bifurcated and running far away",
"none",
"yellowish, compact and fibrous",
"fruity",
"sweet to spicy",
"color from pale yellow to golden yellow, sometimes orange",
"false chanterelle",
"",
"edible, delicious, it can be prepared in many ways"),
("false_chanterelle",
"false_chanterelle",
"lisówka pomarańcziowa",
false,
"POISONOUS",
"autumn",
"deciduous and coniferous forests",
"2-7cm, at first inverted edge, later funnel-shaped, with folded or bent edges, orange-yellow",
"height 3–5 cm, thickness 3–10 mm, cylindrical at the bottom, widening up conically, color blackish at the base",
"none",
"thin, dense, bifurcating, tapering to the stem, sometimes folded",
"none",
"white or cream, juicy and soft",
"mild",
"bitter and sour",
"from yellow to orange-yellow and orange to red-orange",
"chanterelle",
"",
"inedible, when eaten in larger amounts, it can cause digestive disorders")
;