INSERT INTO animal (
photoURL,
animal_name,
other_names,
animal_type,
animal_size,
description,
remarks) VALUES
("tick",
"tick",
"ixodes ricinus/the castor bean tick/kleszcz pospolity",
"arachnid",
"Reach 11 mm length when engorged with a blood meal",
"External parasites, living by feeding on the blood of mainly mammals, birds. Widely distributed around the world. Transmit diseases such as Lyme disease and tick-borne encephalitis.",
"How to protect yourself: avoid tall grass or thickets, wear light-colored clothes with long sleeves, apply insect repellent to the skin, scan the whole body after being out, get vaccinated against tick-borne encephalitis."),
("deer-ked",
"deer-ked",
"lipoptena cervi/deer ked/strzyżak sarni",
"insect",
"Adults only 5–7 mm in length and brownish in colour, bodies are flat and elastic, making their removal difficult",
"A species of biting fly. Common in Europe. Parasites of deer family members, sucking the blood of the host animals. Once reaches its target, it sheds its wings and starts burrowing through the fur.",
"They may rarely bite humans, producing responses from unnoticeable to highly allergic. How to protect yourself: wear light-colored clothes, camphor drops were once used, but their effectiveness has not been proven, as is the case with insect repellent."),
("deer",
"deer",
"capreolus/roe deer/sarna",
"mammal",
"107–145 cm length, height at the withers 65–94 cm; female body weight 17–47 kg, males 20–65 kg",
"From western Europe to the eastern coast of central Asia. Most numerous in Central European countries.",
"In Poland, in the spring of 2011, the number of roe deer was estimated at 764 thousand. individuals."),
("boar",
"boar",
"sus scrofa/wild boar/dzik",
"mammal",
"On average, it reaches 1.1–1.5m, and the largest individuals up to 2m in body length.",
"Suid native to much of Eurasia and North Africa. ",
"If you meet: not make any sudden movements, if you are unnoticed, calmly move away, otherwise stand still. The female with the young can be aggressive. If the sow is getting ready to attack, run away on a tree.")
;